name: Describe EC2 instances

on:
  push

jobs:
  describe:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
    - name: Describe AWS EC2 instances
      run: aws ec2 describe-instances


